name: rating-dist-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - statsmodels
  - patsy
  - jupyter
  - ipykernel
  - ipywidgets
  - openpyxl
  - tqdm
  - transformers
  - accelerate
  - torchaudio
  - torchvision
  - pytorch
  - setuptools
