name: rating-dist-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - statsmodels
  - patsy
  - jupyter
  - ipykernel
  - openpyxl
  - tqdm
  - transformers
  - pytorch
