name: rating-dist-env
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
  - conda-forge
dependencies:
  - pandas
  - jupyter
  - patsy
  - python=3.12
  - setuptools
  - tqdm
  - transformers
  - pytorch
  - accelerate
  - torchvision
  - statsmodels
  - ipywidgets
  - openpyxl
  - matplotlib
  - torchaudio
  - ipykernel
  - scikit-learn
  - numpy
